### ISSUE TITLE
Resolved: `vnInterleavedDimensions` stack size bug

### ISSUE THREAD

**Issue by DylanMuir** [DylanMuir/TIFFStack#10]
Putting a 1 as the last of `vnInterleavedDimensions` makes `TIFFStack` incorrectly report the number of frames in the `TIFF`.

**Comment by ablot** [comment]
I ran into that problem while using the big stack branch, but any 1 is a problem, not only at the last position.

That works:
`stacks = TIFFStack(p, [], [2,2]);`

But these fail:
`stacks = TIFFStack(p, [], [1,1]);`
`stacks = TIFFStack(p, [], [1,2]);`
`stacks = TIFFStack(p, [], [2,1]);`

(No crash just returns only the first image instead of the reshaped 512x512x900 stack)

**Comment by ablot** [comment]
Maybe resolved by https://github.com/DylanMuir/TIFFStack/pull/11
The `size` function was stopping at the first unitary dimension, not the last. At least with the PR I have that:

```
>> disp(size(TIFFStack(p, [], [1,2])))
   512   512     1     2   450

>> disp(size(TIFFStack(p, [], [1])))
   512   512     1   900

>> disp(size(TIFFStack(p, [], [2,2])))
   512   512     2     2   225

>> disp(size(TIFFStack(p, [], [900, 1])))
   512   512   900

```

(the first 2 were 512 512 before the PR)

**Comment by DylanMuir** [comment]
Thanks @ablot for fixing this bug. Please re-open if you notice another permutation of it.
